/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <title>SoundChain</title>
        <meta name="description" content="SoundChain" />

        <meta property="og:url" content="https://soundchain.io" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="SoundChain" />
        <meta property="og:description" content="SoundChain" />
        <meta
          property="og:image"
          content="https://og-poc-randal923.vercel.app/api/og?username=randal923"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="soundchain.io" />
        <meta property="twitter:url" content="https://soundchain.io" />
        <meta name="twitter:title" content="SoundChain" />
        <meta name="twitter:description" content="SoundChain" />
        <meta
          name="twitter:image"
          content="https://og-poc-randal923.vercel.app/api/og?username=randal923"
        />
      </Head>

      <main>
        <div
          style={{
            backgroundColor: "#2A2A2A",
            borderRadius: "10px",
            width: "500px",
            height: "200px",
            display: "flex",
            padding: "19px",
          }}
        >
          <img
            alt="track album image"
            height="150px"
            width="150px"
            style={{ borderRadius: "10px" }}
            src="https://staging.soundchain.io/_next/image?url=https%3A%2F%2Fsoundchain-api-staging-uploads.s3.us-east-1.amazonaws.com%2F6372f6a0-8b5e-40bb-a7b1-3dc8397ce553&w=828&q=75"
          />

          <div
            style={{
              display: "flex",
              flexDirection: "column",
              marginLeft: "21px",
            }}
          >
            <div style={{ display: "flex" }}>
              <img
                alt="profile image"
                height="45px"
                width="45px"
                style={{ borderRadius: "50%" }}
                src="https://staging.soundchain.io/_next/image?url=https%3A%2F%2Fsoundchain-api-staging-uploads.s3.us-east-1.amazonaws.com%2Fa8080a47-b0ae-40f5-99ac-4ac4153fd120.jpeg&w=48&q=75"
              />
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "flex-start",
                  marginLeft: "10px",
                  gap: "2px",
                }}
              >
                <a
                  href="https://staging.soundchain.io/tracks/635430aa17cc480009c49ab5"
                  style={{
                    fontSize: "16px",
                    color: "white",
                    fontWeight: "600",
                  }}
                >
                  furda_sc
                </a>
                <a
                  href="https://staging.soundchain.io/tracks/635430aa17cc480009c49ab5"
                  style={{
                    fontSize: "14px",
                    color: "darkgray",
                    fontWeight: "500",
                  }}
                >
                  @furda_sc
                </a>
              </div>
            </div>

            <h2 style={{ color: "white" }}>Boombap</h2>
            <div style={{ display: "flex" }}>
              <span style={{ marginRight: "10px", color: "white" }}>
                128 Following
              </span>
              <span style={{ color: "white" }}>30 Followers</span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
